// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: ingestsvc.proto

package ingestsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IngestSvcClient is the client API for IngestSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestSvcClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	IngestFiles(ctx context.Context, in *IngestFilesRequest, opts ...grpc.CallOption) (*IngestFilesResponse, error)
}

type ingestSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestSvcClient(cc grpc.ClientConnInterface) IngestSvcClient {
	return &ingestSvcClient{cc}
}

func (c *ingestSvcClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/ingestsvc.IngestSvc/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestSvcClient) IngestFiles(ctx context.Context, in *IngestFilesRequest, opts ...grpc.CallOption) (*IngestFilesResponse, error) {
	out := new(IngestFilesResponse)
	err := c.cc.Invoke(ctx, "/ingestsvc.IngestSvc/IngestFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestSvcServer is the server API for IngestSvc service.
// All implementations must embed UnimplementedIngestSvcServer
// for forward compatibility
type IngestSvcServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	IngestFiles(context.Context, *IngestFilesRequest) (*IngestFilesResponse, error)
	mustEmbedUnimplementedIngestSvcServer()
}

// UnimplementedIngestSvcServer must be embedded to have forward compatible implementations.
type UnimplementedIngestSvcServer struct {
}

func (UnimplementedIngestSvcServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedIngestSvcServer) IngestFiles(context.Context, *IngestFilesRequest) (*IngestFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestFiles not implemented")
}
func (UnimplementedIngestSvcServer) mustEmbedUnimplementedIngestSvcServer() {}

// UnsafeIngestSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestSvcServer will
// result in compilation errors.
type UnsafeIngestSvcServer interface {
	mustEmbedUnimplementedIngestSvcServer()
}

func RegisterIngestSvcServer(s grpc.ServiceRegistrar, srv IngestSvcServer) {
	s.RegisterService(&IngestSvc_ServiceDesc, srv)
}

func _IngestSvc_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestSvcServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ingestsvc.IngestSvc/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestSvcServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestSvc_IngestFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestSvcServer).IngestFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ingestsvc.IngestSvc/IngestFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestSvcServer).IngestFiles(ctx, req.(*IngestFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestSvc_ServiceDesc is the grpc.ServiceDesc for IngestSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestsvc.IngestSvc",
	HandlerType: (*IngestSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _IngestSvc_Hello_Handler,
		},
		{
			MethodName: "IngestFiles",
			Handler:    _IngestSvc_IngestFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingestsvc.proto",
}
